command
DylanSbogar/griddybot pull request #5
Opened 2024-07-22 11:43 UTC by GitAYYYer

2024-07-22 11:48 UTC, BrodeyYendall approved these changes
LGTM 👍

2024-07-22 11:49 UTC, GitAYYYer commented
LGTM 👍

2024-07-22 11:57 UTC, BrodeyYendall commented on commands/currency-conversion/currencyConversion.test.js
> +        JPY: 80.5,
the conversion rate hasnt been this low in 3 years, this test in inaccurate.

2024-07-22 11:58 UTC, BrodeyYendall requested changes
please update tests with valid data

2024-07-23 09:01 UTC, DylanSbogar commented
Lgtm

2024-07-23 09:01 UTC, merged